### ISSUE TITLE
Running Task List

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/GR-sslcm#208]
> This issue is a smattering of to-dos, grouped by different types. Not all of them justify making separate issues, and oftentimes it is faster to leave a note to do something later than to drop everything and handle it right away.

### Output Plots Rmd

- [x] Figure out numbering system so specific sections can be referenced easily in the main-text (`output: bookdown::html_document2: number_sections: TRUE`).
- [x] Comb through nested sections and use optimal tabset structure for each -- if many sublevels (e.g., noise term diagnostics) use a dropdown
- [x] Consistent y-axis limits on fit to data plots
- [x] Model info tables could be more cleanly displayed in one with two sections
- [x] Brainstorm any potential new content
- [x] Proofread all text, add new text where needed
- [x] Priors headers: "Scale" parameters should be "Process SD" parameters
- [x] #209

### Math Document

- [x] Update how pre-spawn survival is handled

### Sim vs. Obs Rmd

- [ ] Try `sd_log` rather than `cv` to express ratio of inter-annual variability between sim and obs period (see [6/27/2023 meeting notes](https://github.com/bstaton1/GR-sslcm/blob/master/99-admin/meeting-notes/2023-06-27-topics-notes.md))

### Manuscript Content

- [x] #81 
  - [x] Data source 13: harvest rates below BON (remove mention of predation/sea lions)
  - [x] New data source: harvest in tributary
  - [x] Data source 18: no longer fitting to pre-spawn mortality data, used determinisitically
  - [x] Data source 20: include "time-varying" with fecundity
  - [x] Different arrow type for spawners $\to$ eggs? It's not really an apportionment rate, maybe label it "generational link"?
- [x] Make figure: large multipanel plot showing life stages as rows, populations as columns. Each panel is a scatterplot with relationship. E.g., top row is egg-to-parr survival vs. egg production, second is parr mean length vs. egg production, etc.
- [x] Make figure: relationship between capacity and WUL
- [x] Make figure: estimated survival rates, showing life stage, LH type, origin, and population comparisons. Should show interannual variability as well as across year averages.
- [x] Make figure: estimated transition rates unrelated to survival. Similar to above; not sure this will be included in the main text. 
- [x] Side analysis & figure: if fall migrant LH type disappeared, how would arrivals to LGR change in terms of magnitude and interannual variability? *Rationale: fall migrants are more rare, but have higher survival. Magnitude is related to how different survival is and how many parr become fall migrants. Portfolio effects -- stabilizing effect only if overwinter survival is non synchronous. Interesting example of an inference facilitated by the integrated model).
- [x] Make figure: correlation parameters -- adapt the version included in output-plots.Rmd, but make grey scale & use consistent formatting with other figures
- [x] Brainstorm 1-2 more ideas for example inferences facilitated by the integrated model
