### ISSUE TITLE
Make overwinter survival density dependent

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/GR-sslcm#27]
Use logistic function with LH-specific intercepts, LH-common slopes, and year-specific random deviations. 

The year-specific deviations should be LH-specific. For now, build them as independent between LH-strategies, but this is a good candidate for introducing some covariance structure (i.e., plausible to expect good and poor winter survival conditions are similar between spring and fall migrants).

**Task list**
- [x] source `00-data/env-data-prep.R` at the top of `02-model/fit-model.R`
- [x] add `PEU` to `create_jags_data_one()`
- [x] add `PEU` to `create_jags_data_mult()`
- [x] add `gamma0[i]` and `gamma1[i]` to model parameters
- [x] implement usage of `gamma` coefficients to produce deterministic predictions of LH-specific overwinter survival
- [x] implement random deviations around deterministic overwinter survival relationship
- [x] add `gamma0[i]` and `gamma1[i]` to tracked nodes
- [x] add plots showing the logistic relationships
