### ISSUE TITLE
Make pre-spawn survival an estimated quantity

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/GR-sslcm#30]
The model currently does not estimate pre-spawn survival, but rather takes an assumed value (of 0.9 for all years and populations).

Using the carcass recovery data, we have the information necessary to estimate it within the model. An exploratory analysis (results sent to collaborators by Staton on 9/22/2020) found that:

1. Inter-annual variability is high for some populations, low for others
2. Some populations have higher pre-spawn survival than others
3. Incorporating covariates for origin or age did not consistently explain variation in spawning status upon recovery
4. There is some limited evidence that pre-spawn survival covaries among populations

Based on these findings, we should add a hierarchical term for pre-spawn survival, with parameters:

* `mu_phi_Sb_Sa`: expected value in any year
* `sig_Lphi_Sb_Sa`: sd of logit-scale year-specific values
* `phi_Sb_Sa[y]`: year-specific values, independent logit-normal random variables

The carcass recovery data need to be aggregated by population and year for fitting using a binomial distribution.

**Task List**

- [x] In `00-data/prep-bio-data.R`: add a section to calculate the number of carcasses sampled and the number found to **have successfully spawned** (females only)
- [x] In `create_jags_data_one()`: extract this info to pass to JAGS
- [x] In `create_jags_data_mult()`: add stuff to combine this info across populations
- [x] In `append_no_na_indices()`: add stuff to add the no NA indices for this info
- [x] In `02-model/fit-model.R`: remove the passed known value of `mu_phi_Sb_Sa`, and monitor the nodes that will now be estimated
- [x] In JAGS model, add hierarchical estimation of pre-spawn survival
- [x] In JAGS model, add binomial likelihood for fitting to carcass data
- [x] In post-processing code, add visuals for the fit to these data
