### ISSUE TITLE
Build in survival data for hatchery releases to LGD

### ISSUE THREAD

**Issue by bstaton1** [bstaton1/GR-sslcm#50]
Although the exact method we will use to aggregate raceway specific survivals to total hatchery survival to LGD is undetermined at this point (see issue [#9](https://github.com/gibsonpp/GR-sslcm-data/issues/9) from the GR-sslcm-data repo), we have enough to build this part into the model, and if the estimates change down the road that is okay. 

This will have several benefits:

* We will be able to calculated derived SARs in a more consistent manner: LGD to tributary compared between hatchery and natural fish, currently we can only compare tributary smolt to tributary adult
* Will facilitate exploring methods of fitting to hydropower survival data and estimating ocean survival/maturity. Currently, the survival term for hatchery fish from release includes migration to LGD and through the hydrosystem, whereas for natural fish it is from LGD through hydrosystem. Any hydrosystem survival data we get will likely be LGD to BON, so we need to have this part be standardized for hatchery and natural fish, i.e., both types will need to have survival from tributary to LGD. 

**Task list**
- [x] Add data processing for hatchery survival estimates
- [x] Add new parameters for this part of the life cycle: across year mean, variability, and year-specific random effects
- [x] Add a fit plot to the output plots
